services:
  node:
    container_name: last-app-node
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    restart: on-failure
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    command: sh -c "npm install && npm run start:dev"